version: "1.0.0"
services:
  api:
    build:
      context: api
    image: docker.io/africodes/api
    expose:
      - 8000
    container_name: api
    restart: always
    networks:
      - web-app

  frontend:
    build:
      context: frontend
    image: docker.io/africodes/frontend
    ports:
      - 3000:3000
    container_name: frontend
    restart: always
    networks:
      - web-app
networks:
  web-app:
